### ISSUE TITLE
Create `.github` repo with `README`

### ISSUE THREAD

**Issue by kenodegard** [conda/infra#617]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

We'd like to add a org level `README.md` to link `conda-incubator`, `conda`, and `conda-archive`. Can also link in other communication channels (e.g. discord, slack, twitter, etc.).

### Why is this needed?

Improves connections between the different parts of the conda ecosystem and boosts discoverability.

### What should happen?

Create `.github` repo and add `README`.

Ref:
- https://github.blog/changelog/2021-09-14-readmes-for-organization-profiles/
- https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile#adding-a-public-organization-profile-readme

**Comment by jezdez** [comment]
I’ve created the repo and added it to the “conda-core” team’s repos, to kick things off
