### ISSUE TITLE
ENH: Make `zstd` compressed index files available

### ISSUE THREAD

**Issue by corneliusroemer** [conda/infra#648]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Right now, conda channel servers provide `.bz2` compressed indexes. That's alright, but bz2 isn't really state of the art anymore. Instead, `zstd` has quickly taken over for fast compression/decompression with good compression ratios.

It would be great if you could offer `zstd` compressed indexes in addition to `bz2` and on the fly `gzip` compressed ones.

### Why is this needed?

Mamba channel index downloads are currently rate limited by gzip server compression (see https://github.com/conda/infra/issues/637).

While this issue could eventually get fixed, mamba developers have stated that they are not keen to add `bz2` support to `mamba` and instead would prefer `zstd` compressed indexes.

It would be great if either #637 or this issue could be implemented fairly soon as it does cause mamba to be quite a bit slower than it should be.

### Additional Context

See here for @wolfv's proposal to add `zstd` compressed indexes: https://github.com/mamba-org/mamba/issues/2021#issuecomment-1281937706 :

>I am not a big fan of the added complexity of using bz2 encoded files and I also don't like bz2 anymore (zstd would be cool!).

**Comment by jezdez** [comment]
Thanks for opening this issue, that seems reasonable to me, but I'm wondering if @barabo has opinions on this?

**Comment by corneliusroemer** [comment]
On the fly `zstd` isn't a bad idea - it should be faster than `gz` compression - but at which point would you implement this? Who would do the compression, cloudflare?

**Comment by dholth** [comment]
Not sure, we're talking about anaconda.org dynamically generated channels and not defaults / conda-forge static hosted channels?

**Comment by corneliusroemer** [comment]
I'm not quite sure what the difference is. The purpose is to speed up download of things like `https://conda.anaconda.org/conda-forge/linux-64/repodata.json` which is currently limited to ~30MB/s even if gzipped because cloudflare gzip on-the-fly compression can't do faster than this.

I don't know whether `conda-forge/linux-64/repodata.json` is dynamic or static.

**Comment by dholth** [comment]
It is available for repo.anaconda.com defaults. It will be available on conda-forge after the channel clone system update is deployed.

**Comment by jezdez** [comment]
Quick note that Anaconda is on a company holiday today.

**Comment by dholth** [comment]
@corneliusroemer repodata.json.zst should be available on conda-forge, and on repo.anaconda.com/main (defaults)!

Please experiment. Is it byte-identical? Are the caches invalidated at the same time? How's the speed?

**Comment by corneliusroemer** [comment]
@dholth that's fantastic new 🎉 

I can confirm that `conda-forge` has `repodata.json.zst` available now, and it downloads really fast in ~1s for me:
```
❯ curl -L https://conda.anaconda.org/conda-forge/linux-64/repodata.json.zst -o test.json.zst     
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24.0M  100 24.0M    0     0  20.3M      0  0:00:01  0:00:01 --:--:-- 20.2M
```

There seem to be some differences, most notably the `zst` repodata has extra lines: `license_family` in a lot of packages, and also some extra packages.

Here is a diff from zstd to uncompressed: 
[diff.txt](https://github.com/conda/infra/files/10239757/diff.txt)

Calculated as follows:
```
ncov-ingest on  master [$✘!?] via 🐍 v3.10.8 via 🅒 nextstrain took 44s 
❯ curl -L https://conda.anaconda.org/conda-forge/linux-64/repodata.json >uncomp.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  225M  100  225M    0     0  37.2M      0  0:00:06  0:00:06 --:--:-- 42.4M

ncov-ingest on  master [$✘!?] via 🐍 v3.10.8 via 🅒 nextstrain took 6s 
❯ curl -L https://conda.anaconda.org/conda-forge/linux-64/repodata.json.zst | zstdcat >zstd.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24.0M  100 24.0M    0     0  29.9M      0 --:--:-- --:--:-- --:--:-- 29.9M

ncov-ingest on  master [$✘!?] via 🐍 v3.10.8 via 🅒 nextstrain took 14s 
❯ json-diff zstd.json uncomp.json >diff.txt
```

So the zstd compressed appears to be a superset of uncompressed.

cc @jonashaag for your PR for mamba support

**Comment by dholth** [comment]
@corneliusroemer try a cache-busting technique like curl <url>?random, or curl -I <url> (what is last-modified)

**Comment by dholth** [comment]
Was your repodata.json older than your repodata.json.zst then?

**Comment by corneliusroemer** [comment]
The differences were reproducible - it wasn't because I downloaded on just before the other.

So it looks like it was a cache thing. I didn't check last-modified headers. I'll play more with it and will see whether it is indeed just a stale cache.

**Comment by dholth** [comment]
We will check the cache invalidation logic.

**Comment by dholth** [comment]
Better: `% curl -I https://conda-static.anaconda.org/conda-forge/linux-64/current_repodata.json.bz2 | grep last-modified ; date -u` should be within 10-20 minutes of each other now.

**Comment by corneliusroemer** [comment]
Works for me. What's the difference between `repodata` and `current_repodata`?

```
❯ curl -I https://conda.anaconda.org/conda-forge/linux-64/current_repodata.json.zst | grep last-modified ; date -u
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 6282k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
last-modified: Thu, 15 Dec 2022 23:28:47 GMT
Thu Dec 15 23:47:47 UTC 2022

❯ curl -I https://conda.anaconda.org/conda-forge/linux-64/current_repodata.json | grep last-modified ; date -u 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 54.3M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
last-modified: Thu, 15 Dec 2022 23:28:47 GMT
Thu Dec 15 23:47:54 UTC 2022

**Comment by dholth** [comment]
Current is the newest version of everything plus its dependencies. Conda tries that first.
